<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2014.2.1.284
*/

require_once('form_process.php');

$form = array(
	'subject' => 'PUBLICATIONS AND VIDEOS Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'jacqueline_jones@me.com',
		'to' => 'jacqueline_jones@me.com'
	),
	'fields' => array(
		'custom_U12270' => array(
			'type' => 'string',
			'label' => 'Type of Publication',
			'required' => false,
			'errors' => array(
			)
		),
		'Email' => array(
			'type' => 'email',
			'label' => 'Year of Publication',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Year of Publication\' is required.',
				'format' => 'Field \'Year of Publication\' has an invalid email.'
			)
		),
		'custom_U12280' => array(
			'type' => 'string',
			'label' => 'Title Keyword',
			'required' => false,
			'errors' => array(
			)
		)
	)
);

process_form($form);
?>
